"""add user email_alerts_enabled

Revision ID: 14ee3b189f2b
Revises: 3820f2cc360c
Create Date: 2026-05-09 22:18:38.455226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ee3b189f2b'
down_revision = '3820f2cc360c'
branch_labels = None
depends_on = None


def upgrade():
    # SQL Server requires a server_default to add a NOT NULL column to a
    # populated table; drop it afterwards so future inserts use the model default.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'email_alerts_enabled', sa.Boolean(), nullable=False,
                server_default=sa.text('1'),
            )
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_alerts_enabled', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_alerts_enabled')

    # ### end Alembic commands ###
