"""add view_count and CarView

Revision ID: 3820f2cc360c
Revises: 76c295ff8e63
Create Date: 2026-05-09 22:00:24.434067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3820f2cc360c'
down_revision = '76c295ff8e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('viewed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_view', schema=None) as batch_op:
        batch_op.create_index('ix_car_view_car_date', ['car_id', 'viewed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_view_car_id'), ['car_id'], unique=False)
        batch_op.create_index('ix_car_view_dedupe_session', ['car_id', 'session_key', 'viewed_date'], unique=False)
        batch_op.create_index('ix_car_view_dedupe_user', ['car_id', 'user_id', 'viewed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_view_session_key'), ['session_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_view_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_view_viewed_date'), ['viewed_date'], unique=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'view_count', sa.Integer(), nullable=False,
                server_default=sa.text('0'),
            )
        )

    # Drop the server-side default once existing rows have been backfilled, so
    # future inserts rely on the model-level default (Python-side).
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('view_count', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    with op.batch_alter_table('car_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_view_viewed_date'))
        batch_op.drop_index(batch_op.f('ix_car_view_user_id'))
        batch_op.drop_index(batch_op.f('ix_car_view_session_key'))
        batch_op.drop_index('ix_car_view_dedupe_user')
        batch_op.drop_index('ix_car_view_dedupe_session')
        batch_op.drop_index(batch_op.f('ix_car_view_car_id'))
        batch_op.drop_index('ix_car_view_car_date')

    op.drop_table('car_view')
    # ### end Alembic commands ###
