"""baseline + messaging offers test_drives saved_searches reports notifications admin

Revision ID: 76c295ff8e63
Revises: 
Create Date: 2026-05-09 21:32:26.785688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c295ff8e63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # SQL Server requires a default when adding NOT NULL columns to non-empty
    # tables. We add the column with a server-side default of false (0), then
    # drop the default so future inserts use the model-level default instead.
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_taken_down',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.create_index(batch_op.f('ix_car_is_taken_down'), ['is_taken_down'], unique=False)
        batch_op.alter_column('is_taken_down', server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_admin',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.alter_column('is_admin', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_is_taken_down'))
        batch_op.drop_column('is_taken_down')

    # ### end Alembic commands ###
